### ISSUE TITLE
HTML output has a dark blue background with black text by default

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dart-pad#1547]
Playing with the HTML library is hindered by the default color scheme in the output area. The text is black and the background color is dark enough that it is very difficult to read and bad for accessibility.

To repro run this in dartpad:
```dart
import 'dart:html';

main() {
  document.body.setInnerHtml('Hello World');
}
```

The output looks like this. If you squint or turn up the brightness on your screen you might be able to read the text: 
![Screen Shot 2020-04-28 at 4 12 43 PM](https://user-images.githubusercontent.com/2498387/80546663-1ed4f400-896b-11ea-871c-6e76a426d4fa.png)

Dragging the mouse to highlight it makes it easier to read.

**Comment by sperochon** [comment]
Hi,

I'm facing the same problem with the flutter code:
`import 'package:flutter/material.dart';

void main() {
  runApp(
    const Text(
        'Hello, world!',
        textDirection: TextDirection.ltr,
      ),
  );
}`

The output on Android emulator or on real Android device is not the same as the one in dartpad since the text is displayed in light grey as following:
![Capture d’écran 2021-10-01 à 09 41 47](https://user-images.githubusercontent.com/1877340/135583663-d41f6ef9-1fd2-4617-8709-4053e39193d7.png)

**Comment by RedBrogdon** [comment]
Interesting. For the first bit, this has definitely come up before. We'd have a bit of an issue changing it at this point, since so many of the pads we've created since the redesign was launched assume a dark background. Could we solve this by adding a color:white to the CSS that's included with new HTML pads? Right now it's there for `h1`, but no other tags:

```css
body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  position: absolute;
  width: 100%;
  height: 100%;
}

h1 {
  color: white;
  font-family: Arial, Helvetica, sans-serif;
}
```

For the second question (Android behavior), I'm not sure if Flutter actually guarantees a text color if no text style is given to a Text widget. @hansmuller do you happen to know?
