### ISSUE TITLE
Dartpad cannot display flag emojis

### ISSUE THREAD

**Issue by sma** [dart-lang/dart-pad#1799]
I tested both Chrome 91 and Firefox 87 on macOS 11.2 but [this example](https://dartpad.dev/b46251adf74bc4f1b5eba86f003d754d?null_safety=true) doesn't display flags like for example 🇺🇳.

I see his error on the console (12 times):

```
dart_sdk.js:102698 Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts
```

**Comment by domesticmouse** [comment]
Can you please add a minimal reproduction case so we can look into how to fix this issue plz? Thanks!

**Comment by domesticmouse** [comment]
Hey John, any ideas on what I need to do here? I tried building a Flutter app for web including https://www.google.com/get/noto/#emoji-zsye-color as a custom font as follows:

```
name: dartpad_sample
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
```

But it is still rendering as UN. Any ideas?

<img width="109" alt="Screen Shot 2021-04-01 at 10 32 18 am" src="https://user-images.githubusercontent.com/30503/113223726-932fba00-92d5-11eb-967d-bfb8106580cf.png">
