### ISSUE TITLE
Improve organization of dropdown samples

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2322]
Once we land https://github.com/dart-lang/dart-pad/pull/2320, we will have a Provider and Riverpod sample, but we should consider breaking up the dropdown into sections such as "Flutter", "State Management", etc.

**Comment by timmaffett** [comment]
After reading @domesticmouse  's first comment about submenus in #2320 I started looking into possible solutions to the sample menu, and the possibilities of submenus, etc.
My general thought on a possible direction to go here is this:

Instead of having the samples hard coded in _buildSamplesMenu() it would be nice to instead create a class that would:
  1) access a private gist (owned by dart-lang) which contains a yaml file that contains the definition of the samples menu
  2) load the yaml file and build the samples menu accordingly.  This would also be nice because it could handle the creation of the submenus defined within the yaml file, as this will be more complex than the current system of creating a single simple menu within _buildSampleMenu().  If we continued the current system of hard coding the menu creation within the the code then the simplest change, such as adding a new submenu category, would necessitate significantly more complex code changes.

The menu definition file could be something like this (somewhat contrived examples):


------ samples_menu.yaml ------------
```yaml
menu: Samples
  - submenu: State Management
    - menuitem: Provider
      gist: a133148221a8cbacbcef8bc77a6c82ec
      layout: flutter
    - menuitem: Riverpod
      gist: ab876afc97987ab876afc97987
      layout: flutter
  - submenu: Flame Game Framework
    - menuitem: Pod Racer
      gist: 97abc89797dfab876afc64534187
      layout: flutter
    - menuitem: Tic Tac Toe
      gist: 35464afc293dab876afc912387
      layout: flutter
  - submenu: Dart Examples
    - menuitem: Hello World
      gist: c0f7c578204d61e08ec0fbc4d63456cd
      layout: dart
    - menuitem: Fibonacci
      gist: d3bd83918d21b6d5f778bdc69c3d36d6
      layout: dart
    - menuitem: HTTP Requests
      gist: 4a68e553746602d851ab3da6aeafc3dd
      layout: dart
 
... and so on, you get the idea
```

(The yaml file could also be in a regular repository (such as dart-pad), but since the samples are gists, and our gist loader class already exists, ...)
(Some other file format could be used for the menu definition, but yaml seems like a natural fit for something like a menu definition with nested submenus, and we already include a yaml file parser).

I started to play with this already, but I am looking for a nice example of programmatically creating mdc-menu's with nested submenus..  can anyone recommend any ? (i did some simple google searches and didn't immediately find anything, or in the documentation, so I thought I would ask). 

thoughts?
