### ISSUE TITLE
Support analyzer flags

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#783]
related to #759 

It would be great to be able to switch analyzer options like
```yml
  strong-mode:
    declaration-casts: false
    implicit-casts: false
    implicit-dynamic: false
```
